name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@master
        with:
          command: install
          args: rojo
      - name: Build
        run: rojo build plugin.project.json --output plugin.rbxmx
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: plugin
          path: plugin.rbxmx